package oopfinal;

import javax.swing.JOptionPane;

/**
 *
 * @author borao
 */
public class LoginMenu extends javax.swing.JFrame {

    public static String savedUserAccNo = "";

    public LoginMenu() {

        initComponents();
        RegisterMenu.bankDetailsList.clear();
        RegisterMenu.populateBankDetailsList();
        accountNoLogin.setText(savedUserAccNo);

    }

    public static boolean numberOrNot(String input) {
        try {
            Integer.parseInt(input);
        }
        catch (NumberFormatException ex) {
            return false;
        }

        return true;
    }

    public static boolean isSixDigit(String accNo) {
        if (numberOrNot(accNo)) {
            return String.valueOf(accNo).length() == 6;
        }
        else {
            return false;
        }
    }

    public static boolean isFourDigit(String accNo) {
        if (numberOrNot(accNo)) {
            return String.valueOf(accNo).length() == 4;

        }
        else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accountNoLogin = new javax.swing.JTextField();
        passwordLogin = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forgetPassButton = new javax.swing.JLabel();
        LoginButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RegisterButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bank");
        setBackground(new java.awt.Color(204, 204, 204));
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(291, 361));
        setMinimumSize(new java.awt.Dimension(291, 361));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(186, 186, 186));

        accountNoLogin.setBackground(new java.awt.Color(255, 255, 255));
        accountNoLogin.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        accountNoLogin.setBorder(null);

        passwordLogin.setBackground(new java.awt.Color(255, 255, 255));
        passwordLogin.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        passwordLogin.setBorder(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Login");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel4.setText("Account No:");

        forgetPassButton.setBackground(new java.awt.Color(0, 0, 102));
        forgetPassButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        forgetPassButton.setForeground(new java.awt.Color(51, 0, 102));
        forgetPassButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgetPassButton.setText("Forget Account Number");
        forgetPassButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetPassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgetPassButtonMouseClicked(evt);
            }
        });

        LoginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setMaximumSize(new java.awt.Dimension(140, 55));
        LoginButton.setMinimumSize(new java.awt.Dimension(140, 55));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        javax.swing.GroupLayout LoginButtonLayout = new javax.swing.GroupLayout(LoginButton);
        LoginButton.setLayout(LoginButtonLayout);
        LoginButtonLayout.setHorizontalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        LoginButtonLayout.setVerticalGroup(
            LoginButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        RegisterButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        RegisterButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterButton.setMaximumSize(new java.awt.Dimension(48, 35));
        RegisterButton.setMinimumSize(new java.awt.Dimension(48, 35));
        RegisterButton.setPreferredSize(new java.awt.Dimension(48, 35));
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Register");

        javax.swing.GroupLayout RegisterButtonLayout = new javax.swing.GroupLayout(RegisterButton);
        RegisterButton.setLayout(RegisterButtonLayout);
        RegisterButtonLayout.setHorizontalGroup(
            RegisterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        RegisterButtonLayout.setVerticalGroup(
            RegisterButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accountNoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(forgetPassButton)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(RegisterButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                        .addComponent(LoginButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountNoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgetPassButton)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(353, 402));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void forgetPassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetPassButtonMouseClicked
        new ForgetPasswordMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_forgetPassButtonMouseClicked

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        // Check if the account number and password fields are empty
        if (this.accountNoLogin.getText().isEmpty() || this.passwordLogin.getText().isEmpty()) {
            // Display error message if either field is empty
            JOptionPane.showMessageDialog(null, "You Have To Fill All The Details!");
            return;
        }
        if (!isSixDigit(this.accountNoLogin.getText())) {
            // Display error message if the account number is not a 6-digit string
            JOptionPane.showMessageDialog(null, "Account No must be 6 digit long and Cannot contain any special characters!");
            return;
        }
        if (!isFourDigit(this.passwordLogin.getText())) {
            // Display error message if the password is not a 4-digit string
            JOptionPane.showMessageDialog(null, "Password must be 4 digit long and cannot Contain any special characters!");
            return;
        }

        // If both the account number and password are in the correct format, search for a matching account number in the bankDetailsList
        String accNoInput = this.accountNoLogin.getText().trim();
        int userIndex = MainBankMenu.findBankDetailsByAccNo(accNoInput);
        
            BankDetails userDetails = RegisterMenu.bankDetailsList.get(userIndex);
            // If a matching account number is found, store the account number and retrieve the BankDetails object
            if (Integer.parseInt(userDetails.getAccNo()) == Integer.parseInt(accNoInput)) {
                
                MainBankMenu.userAccNo = userDetails.getAccNo();
                
            }
        

        // If the account number is not found, display an error message
        if (userIndex == -1) {
            JOptionPane.showMessageDialog(null, "Your Account Number or Password is invalid!");
        }
        else {
            // If the account number is found, retrieve the BankDetails object and check if the password matches
            
            if (!userDetails.getPassword().equals(this.passwordLogin.getText().trim())) {
                // Display error message if the password is incorrect
                JOptionPane.showMessageDialog(null, "Your Account Number or Password is invalid!");
            }
            else {
                // If the password is correct, display a success message and show the MainBankMenu form
                JOptionPane.showMessageDialog(null, "Successfully logged in!\nHello " + userDetails.getName());

                new MainBankMenu().setVisible(true);
                dispose();

            }
        }
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterButtonMouseClicked
        new RegisterMenu().setVisible(true);
        dispose();
    }//GEN-LAST:event_RegisterButtonMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginMenu().setVisible(true);
            }

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginButton;
    private javax.swing.JPanel RegisterButton;
    private javax.swing.JTextField accountNoLogin;
    private javax.swing.JLabel forgetPassButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordLogin;
    // End of variables declaration//GEN-END:variables

}
